### ISSUE TITLE
Use `fs.statSync`?

### ISSUE THREAD

**Issue by joliss** [ember-cli/exists-sync#2]
Currently, `fs.existsSync` is [implemented in terms of `fs.statSync`](https://github.com/nodejs/node/blob/68dc69a382692f424c53b75724e684a406b195a1/lib/fs.js#L216-L224). I think this module can copy that logic and be much simpler as a result.

`statSync` already follows symlinks automatically and throws an ENOENT error on broken symlinks, unlike `lstatSync`, so no special handling is needed for that.

**Comment by trabus** [comment]
@joliss I'm absolutely open to doing that, I don't know why I didn't realize stat followed symlinks.

I'll try and find some time to refactor this weekend.

**Comment by stefanpenner** [comment]
Thanks guys

**Comment by trabus** [comment]
@joliss I tried swapping in statSync instead of lstatSync, but I'm unable to get it working with my tests. :(
It refuses to follow the symlinks I've setup in my tests, and throws ENOENT errors on symlinks that worked with lstatSync. Maybe I'm doing something wrong with my setup?

**Comment by nathanhammond** [comment]
[`fs.existsSync` has been un-deprecated.](https://github.com/nodejs/node/pull/8364#issuecomment-251770246) Any further changes to this should only address known bugs. In light of that I'm closing this issue.
